### ISSUE TITLE
Deploy documentation to GitHub Pages

### ISSUE THREAD

**Issue by yonch** [perfpod/memory-collector#10]
We created a `gh-pages` branch to this repository, and https://perfpod.github.io/memory-collector/ points to the README.md.

In this ticket, we create
- [ ] a `docs` directory in the repo
- [ ] an initial readme (can be the first few paragraphs of the README.md for now)
- [ ] an initial `mkdocs.yml`
- [ ] a GitHub Actions to publish to the `gh-pages` branch. There are instructions on the `MkDocs` page: [link](https://www.mkdocs.org/user-guide/deploying-your-docs/#project-pages). This would probably involve using a good docker container and perhaps fetching the MkDocs dependencies.

I've had previous success with the following python deps:
```
mkdocs
pymdown-extensions
mkdocs-material
mkdocs-bibtex
mkdocs-awesome-pages-plugin
```

here is a reference `mkdocs.yml`:
```
site_name: 'PerfPod docs'
site_url: https://state-fu.com/docs
nav:
  - Home: 'README.md'
theme: material
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - attr_list

plugins:
  - search
  - awesome-pages
```
